DDCNL-9718 Adding step to deallocate enrolments from groups when no u…
hmrc/tax-enrolment-assignment-frontend pull request #188
Opened 2024-12-13 09:09 UTC by Nj147

…ser has the enrolment

2024-12-18 09:23 UTC, grantrobson approved these changes
lgtm

2024-12-20 16:07 UTC, pascal22p requested changes

2024-12-20 16:07 UTC, pascal22p commented on app/uk/gov/hmrc/taxenrolmentassignmentfrontend/connectors/EACDConnector.scala
> +          Right(response.json.as[GroupsAssignedEnrolment](GroupsAssignedEnrolment.reads))
This does match the type of the method: Either[UpstreamErrorResponse, HttpResponse]
Use a HttpResponse in the connector. No need to parse into an object.

2024-12-20 16:11 UTC, pascal22p requested changes

2024-12-20 16:11 UTC, pascal22p commented on app/uk/gov/hmrc/taxenrolmentassignmentfrontend/services/EACDService.scala
> +    eacdConnector.getGroupsFromEnrolment(s"$hmrcPTKey~NINO~${requestWithUserDetails.userDetails.nino}")
```suggestion
    eacdConnector.getGroupsFromEnrolment(s"$hmrcPTKey~NINO~${requestWithUserDetails.userDetails.nino}").map { response => 
    val json = response.json
    val principals = (json / "principalGroupsId").readNullable[List[String]]
    val delegated = (json / "delegatedGroupsId").readNullable[List[String]]
    principals.getOrlElse(List.empty) ++ delegated.getOrElse(List.empty)
    }
```

2024-12-20 16:11 UTC, pascal22p commented on app/uk/gov/hmrc/taxenrolmentassignmentfrontend/models/GroupsAssignedEnrolment.scala
> +case class GroupsAssignedEnrolment(groupIds: List[String])
Overkill for what it contains

2024-12-20 16:12 UTC, pascal22p requested changes

2024-12-20 16:12 UTC, pascal22p commented on app/uk/gov/hmrc/taxenrolmentassignmentfrontend/services/EACDService.scala
> +  ): TEAFResult[GroupsAssignedEnrolment] =
```suggestion
  ): TEAFResult[List[String]] =
```

2025-01-03 12:52 UTC, pascal22p approved these changes

2025-01-03 12:55 UTC, pascal22p approved these changes

2025-01-07 12:55 UTC, SandeepUmredkar approved these changes

2025-01-07 13:15 UTC, merged