TEN-84 Current ID confirmation Page
hmrc/tax-enrolment-assignment-frontend pull request #29
Opened 2022-03-11 11:52 UTC by TSiyamachiraQA

2022-03-14 08:57 UTC, Chrissystk requested changes

2022-03-14 08:57 UTC, Chrissystk commented on test/uk/gov/hmrc/taxenrolmentassignmentfrontend/controllers/views/CurrentIdConfirmationSpec.scala
> +  private val testNino = "testNino"
Think this should be currentId

2022-03-14 08:57 UTC, Chrissystk commented on test/uk/gov/hmrc/taxenrolmentassignmentfrontend/controllers/views/CurrentIdConfirmationSpec.scala
> +    }
In other view tests we have created messagesFiles in the test folder messages. It is better to be consistent across all tests.

2022-03-25 15:21 UTC, Ufuoma-Daniel approved these changes

2022-03-25 17:18 UTC, closed without merging